# Generated by Django 3.2.7 on 2021-10-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.CharField(max_length=30)),
                ('econtact', models.CharField(max_length=15)),
                ('lugarr', models.CharField(max_length=50)),
                ('cedulaa', models.CharField(max_length=40)),
                ('usuarioo', models.CharField(max_length=60))
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
